### ISSUE TITLE
CALCE数据处理代码得到的数据和保存的npy文件数据结果不一致的问题

### ISSUE THREAD

**Issue by CXL-edu** [XiuzeZhou/RUL#3]
![O 4LS$6XUG$YTLH$~ZVTU~G](https://github.com/XiuzeZhou/RUL/assets/60612507/bb687e58-44a7-4e2d-b475-2c9a473a1a48)
![78UVBFWDB~6~F$ITLIIR`G6](https://github.com/XiuzeZhou/RUL/assets/60612507/7cd75aab-d959-4ae0-a159-e5d6f049f97e)
这两幅图分别是使用Transformer - CALCE.ipynb文件中，从原始xlsx文件中读取数据绘制CS2_35的图片和使用从npy文件中读取的数据绘制的图片。明显从原始数据中读取的包含很多噪声和离群值。请问作者是对原始容量进行平滑或者是提取了数据的主要模态分量吗？

**Comment by XiuzeZhou** [comment]
请查看你是否改了原始代码而忘了加drop_outlier函数来对数据进行过滤？

**Comment by XiuzeZhou** [comment]
> 

请查看你是否改了原始代码而忘了加drop_outlier函数来对数据进行过滤？

**Comment by CXL-edu** [comment]
感谢回复，确实是因为注释掉了drop_outlier函数。
